/**
 * constraint-builder-ui.spec.ts
 *
 * SB2-09-03 UI verification — drive the visual ConstraintBuilder
 * (Comparación preset) end-to-end through the survey builder v2 and verify
 * the resulting `constraint_expression` is persisted in the survey detail
 * payload exactly as the JSONLogic AST `{"==":[{"var":"answers.<key>"}, ...]}`.
 *
 * Scope notes:
 *   - Comparison preset's LHS is ALWAYS the question's own `question_key`
 *     (`answers.<ownKey>`), never cross-question. Cross-question constraints
 *     would require the "Avanzado" preset (raw JSON textarea) and are out
 *     of scope for this spec.
 *   - The builder v2 is currently create-only (handleSave shows
 *     "Edición no disponible aún" for existing surveys), so we exercise the
 *     create-survey path and verify via GET /admin/surveys/{id}.
 *   - `question_key` is auto-generated by the builder; we look up the
 *     created question by `question_text` rather than by key.
 *
 * Auth: role_1 (admin). Cleanup: DELETE survey in finally block.
 */

import { expect, test } from "@playwright/test";
import { getCredentialByRoleNumber } from "../fixtures/credentials.js";
import { LoginPage } from "../pages/login.page.js";

const adminCredential = getCredentialByRoleNumber(1);

const SURVEY_TITLE = `QA-SB2-09-03-ConstraintBuilderUI ${Date.now()}`;
const Q1_TEXT = "Pregunta filler";
const Q2_TEXT = "Color obligatorio (debe ser rojo)";
const CONSTRAINT_RHS = "rojo";

test.describe("SB2-09-03 — ConstraintBuilder UI builds correct JSONLogic", () => {
  test.skip(
    !adminCredential,
    "Define E2E_LOGIN_EMAIL_ROLE_1/E2E_LOGIN_PASSWORD_ROLE_1 in .env.",
  );

  test("Comparación preset persists `{\"==\":[{\"var\":\"answers.<key>\"}, value]}` as constraint_expression", async ({
    page,
  }) => {
    test.setTimeout(120_000);

    const loginPage = new LoginPage(page);
    await loginPage.login(adminCredential!);

    let createdSurveyId: number | null = null;
    let cleanedUp = false;
    const cleanup = async () => {
      if (cleanedUp || createdSurveyId == null) return;
      cleanedUp = true;
      const del = await page.request.delete(
        `/api/backend/admin/surveys/${createdSurveyId}`,
      );
      expect([200, 204, 404]).toContain(del.status());
    };

    try {
      // ── 1. Open builder v2 ────────────────────────────────────────────
      await page.goto("/dashboard/surveys/builder");
      await page.waitForLoadState("networkidle");

      // ── 2. Set survey title (SurveyMetaEditor: only visible while
      //      no question is selected). ──────────────────────────────────
      const titleInput = page.getByPlaceholder("Ej: Encuesta de campo Q2");
      await expect(titleInput).toBeVisible({ timeout: 15_000 });
      await titleInput.fill(SURVEY_TITLE);

      // ── 3. Add Q1 (Texto corto). Toolbox group "Básicas" is open by
      //      default; the trigger button shows the type label. ──────────
      const textoCortoButton = page
        .getByRole("button", { name: /^Texto corto/ })
        .first();
      await expect(textoCortoButton).toBeVisible({ timeout: 10_000 });
      await textoCortoButton.click();

      // After addQuestion(), the new question is auto-selected, so
      // BuilderSettings now shows QuestionEditor with the "Enunciado *"
      // textarea.
      const enunciadoTextarea = page.locator(
        'textarea[maxlength="240"]',
      );
      await expect(enunciadoTextarea).toBeVisible({ timeout: 10_000 });
      await enunciadoTextarea.fill(Q1_TEXT);

      // ── 4. Add Q2 (Texto corto) → auto-selected → fill text ─────────
      await textoCortoButton.click();
      // Wait for the new selection to swap the textarea content
      // (controlled component value resets to empty string).
      await expect(enunciadoTextarea).toHaveValue("", { timeout: 10_000 });
      await enunciadoTextarea.fill(Q2_TEXT);

      // ── 5. Open "Restricción de validez" accordion and pick the
      //      Comparación preset. ──────────────────────────────────────
      const restriccionTrigger = page.getByRole("button", {
        name: /Restricción de validez/i,
      });
      await expect(restriccionTrigger).toBeVisible({ timeout: 10_000 });
      await restriccionTrigger.click();

      const comparacionTab = page
        .getByRole("button", { name: /^Comparación$/ })
        .first();
      await expect(comparacionTab).toBeVisible({ timeout: 10_000 });
      await comparacionTab.click();

      // ── 6. Fill RHS with "rojo" (operator defaults to ==) ────────────
      const rhsInput = page.getByPlaceholder(
        "valor (número, texto, true/false)",
      );
      await expect(rhsInput).toBeVisible({ timeout: 10_000 });
      await rhsInput.fill(CONSTRAINT_RHS);

      // ── 7. Save survey ────────────────────────────────────────────────
      const saveButton = page.getByRole("button", { name: /^Crear encuesta$/ });
      await expect(saveButton).toBeEnabled({ timeout: 10_000 });
      await saveButton.click();

      // After successful save, page.tsx does
      //   router.replace(`/dashboard/surveys/builder?surveyId=${id}`)
      await page.waitForURL(/\/dashboard\/surveys\/builder\?surveyId=\d+/, {
        timeout: 30_000,
      });

      const url = new URL(page.url());
      const surveyIdRaw = url.searchParams.get("surveyId");
      expect(surveyIdRaw, "surveyId must be present in URL after save")
        .toBeTruthy();
      const surveyId = Number(surveyIdRaw);
      expect(Number.isFinite(surveyId)).toBeTruthy();
      createdSurveyId = surveyId;

      // ── 8. Fetch survey detail and verify constraint_expression ─────
      const detailResp = await page.request.get(
        `/api/backend/admin/surveys/${surveyId}`,
      );
      expect(
        detailResp.ok(),
        `GET admin/surveys/${surveyId} → ${detailResp.status()}`,
      ).toBeTruthy();
      const detail = await detailResp.json();

      // The first version is the just-created v1.
      const versions: Array<{
        version_number: number;
        questions: Array<{
          question_key?: string | null;
          question_text: string;
          constraint_expression?: unknown;
        }>;
      }> = detail.versions ?? [];
      expect(versions.length, "survey should have at least one version")
        .toBeGreaterThan(0);

      const v1 = versions[0]!;
      const q2 = v1.questions.find((q) => q.question_text === Q2_TEXT);
      expect(q2, `question with text "${Q2_TEXT}" missing in v1`).toBeTruthy();
      const ownKey = q2!.question_key;
      expect(ownKey, "Q2 must have an auto-generated question_key").toBeTruthy();

      // ConstraintBuilder Comparación preset always builds:
      //   { "==": [ { "var": "answers.<ownKey>" }, <rhs> ] }
      expect(q2!.constraint_expression).toEqual({
        "==": [{ var: `answers.${ownKey}` }, CONSTRAINT_RHS],
      });

      // Q1 must have NO constraint (only Q2 was edited).
      const q1 = v1.questions.find((q) => q.question_text === Q1_TEXT);
      expect(q1, `question with text "${Q1_TEXT}" missing in v1`).toBeTruthy();
      // Backend may omit the field or return null when unset; both are fine.
      const q1Constraint = q1!.constraint_expression;
      expect(
        q1Constraint == null,
        `Q1 should not have a constraint_expression, got: ${JSON.stringify(
          q1Constraint,
        )}`,
      ).toBeTruthy();
    } finally {
      await cleanup();
    }
  });
});
